import { IAgency } from '@/interfaces';

export const AGENCIES_DATA: IAgency[] = [
	{
		id: 4,
		name: 'CUENCA',
		modules: [
			{
				id: 1,
				name: 'VEHÍCULOS',
				path: null,
				icon: 'mdiSquareRoundedOutline',
				entorno: 'FRONT',
				submodules: [
					{
						id: 2,
						name: 'GESTIÓN DE COMPRAS',
						path: null,
						icon: 'IconCamion',
						groups: [],
						programs: [
							{
								id: 1,
								name: 'GESTIÓN DE TRÁNSITO',
								path: '/itsa/security/maintenance/modules',
								url: '/itsa/security/maintenance/modules',
								icon: 'IconCamion',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 2,
								name: 'GESTIÓN DE COMPRAS VEHÍCULOS NUEVOS',
								path: '/vehiculos/gestion-compras-nuevos',
								url: '/vehiculos/gestion-compras-nuevos',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 41,
								name: 'GESTIÓN DE COMPRAS VEHÍCULOS USADOS',
								path: '/vehiculos/gestion-compras-usados',
								url: '/vehiculos/gestion-compras-usados',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 42,
								name: 'GESTIÓN DE TRÁNSITO',
								path: '/vehiculos/gestion-transito',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 3,
						name: 'GESTIÓN DE VENTAS',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 3,
								name: 'VENTAS',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 4,
								name: 'AUTORIZACIONES',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 1,
						name: 'MANTENIMIENTOS',
						path: null,
						icon: 'mdiViewModule',
						groups: [
							{
								id: 1,
								name: 'GESTIÓN DE ENTIDADES PERSONALES',
								path: null,
								icon: 'mdiAccount',
								programs: [
									{
										id: 5,
										name: 'CLIENTES',
										path: '/nucleo/gestion-clientes',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 6,
										name: 'TRANSPORTISTAS',
										path: '/nucleo/gestion-transportistas',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 7,
										name: 'COLABORADORES',
										path: '/nucleo/gestion-colaboradores',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 12,
										name: 'PROVEEDORES',
										path: '/nucleo/gestion-proveedores',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
							{
								id: 4,
								name: 'PARÁMETROS Y CONFIGURACIÓN',
								path: null,
								icon: 'mdiCog',
								programs: [
									{
										id: 28,
										name: 'CONSTANTES & PARÁMETROS DEL SISTEMA',
										path: '/nucleo/constantes-y-parametros',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 29,
										name: 'DÍAS DE FERIADO',
										path: '/nucleo/feriados',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
							{
								id: 6,
								name: 'PROCESOS Y DOCUMENTOS LEGALES',
								path: null,
								icon: 'mdiFileDocument',
								programs: [
									{
										id: 30,
										name: 'PEPS',
										path: '/nucleo/peps',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 31,
										name: 'PROVIDENCIAS',
										path: '/nucleo/providencias',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 32,
										name: 'SANCIONADOS ONU',
										path: '/nucleo/sancionados-onu',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 33,
										name: 'OFAC',
										path: '/nucleo/ofac',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
							{
								id: 5,
								name: 'PRECIOS Y VENTAS',
								path: null,
								icon: 'mdiSale',
								programs: [
									{
										id: 34,
										name: 'POLÍTICAS DE PRECIOS',
										path: '/vehiculos/politicas-precios',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 35,
										name: 'PRESUPUESTO DE VENTA',
										path: '/vehiculos/presupuesto-venta',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 36,
										name: 'REGALOS',
										path: '/vehiculos/regalos',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 37,
										name: 'PROMOCIONES',
										path: '/vehiculos/promociones',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 38,
										name: 'VALOR TRADE IN',
										path: '/vehiculos/trade-in',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
							{
								id: 7,
								name: 'GESTIÓN DE VEHÍCULOS, PRODUCTOS Y ACCESORIOS',
								path: null,
								icon: 'mdiCarBack',
								programs: [
									{
										id: 39,
										name: 'GESTIÓN DE MODELOS',
										path: '/vehiculos/modelos',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 40,
										name: 'RASTREO Y SEGURIDAD',
										path: '/vehiculos/rastreo-seguridad',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
						],
						programs: [],
					},
				],
			},
			{
				id: 2,
				name: 'LÍNEA PARA EL HOGAR',
				path: null,
				icon: 'mdiSquareRoundedOutline',
				entorno: 'FRONT',
				submodules: [
					{
						id: 5,
						name: 'GESTIÓN DE COMPRAS',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 13,
								name: 'COMPRAS',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 14,
								name: 'GESTIÓN DE RECEPCIÓN',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 6,
						name: 'GESTIÓN DE VENTAS',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 15,
								name: 'VENTAS',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 16,
								name: 'AUTORIZACIONES',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 4,
						name: 'MANTENIMIENTOS',
						path: null,
						icon: 'mdiViewModule',
						groups: [
							{
								id: 2,
								name: 'GESTIÓN DE ENTIDADES PERSONALES',
								path: null,
								icon: 'mdiAccount',
								programs: [
									{
										id: 17,
										name: 'CLIENTES',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 18,
										name: 'TRANSPORTISTAS',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 19,
										name: 'COLABORADORES',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 23,
										name: 'PROVEEDORES',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
						],
						programs: [],
					},
				],
			},
			{
				id: 6,
				name: 'CARTERA',
				path: null,
				icon: 'mdiSquareRoundedOutline',
				entorno: 'BACK',
				submodules: [
					{
						id: 7,
						name: 'GESTIÓN DE COBRANZA',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 24,
								name: 'ABONOS',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
				],
			},
		],
	},
	{
		id: 6,
		name: 'MACHALA',
		modules: [
			{
				id: 1,
				name: 'VEHÍCULOS',
				path: null,
				icon: 'mdiSquareRoundedOutline',
				entorno: 'FRONT',
				submodules: [
					{
						id: 2,
						name: 'GESTIÓN DE COMPRAS',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 1,
								name: 'GESTIÓN DE TRÁNSITO',
								path: '/itsa/security/maintenance/modules',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 2,
								name: 'GESTIÓN DE COMPRAS VEHÍCULOS NUEVOS',
								path: '/vehiculos/gestion-compras-nuevos',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 41,
								name: 'GESTIÓN DE COMPRAS VEHÍCULOS USADOS',
								path: '/vehiculos/gestion-compras-usados',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 42,
								name: 'GESTIÓN DE TRÁNSITO',
								path: '/vehiculos/gestion-transito',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 3,
						name: 'GESTIÓN DE VENTAS',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 3,
								name: 'VENTAS',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 4,
								name: 'AUTORIZACIONES',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 1,
						name: 'MANTENIMIENTOS',
						path: null,
						icon: 'mdiViewModule',
						groups: [
							{
								id: 1,
								name: 'GESTIÓN DE ENTIDADES PERSONALES',
								path: null,
								icon: 'mdiAccount',
								programs: [
									{
										id: 5,
										name: 'CLIENTES',
										path: '/nucleo/gestion-clientes',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 6,
										name: 'TRANSPORTISTAS',
										path: '/nucleo/gestion-transportistas',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 7,
										name: 'COLABORADORES',
										path: '/nucleo/gestion-colaboradores',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 12,
										name: 'PROVEEDORES',
										path: '/nucleo/gestion-proveedores',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
							{
								id: 5,
								name: 'PRECIOS Y VENTAS',
								path: null,
								icon: 'mdiSale',
								programs: [
									{
										id: 38,
										name: 'VALOR TRADE IN',
										path: '/vehiculos/trade-in',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
						],
						programs: [],
					},
				],
			},
			{
				id: 2,
				name: 'LÍNEA PARA EL HOGAR',
				path: null,
				icon: 'mdiSquareRoundedOutline',
				entorno: 'FRONT',
				submodules: [
					{
						id: 5,
						name: 'GESTIÓN DE COMPRAS',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 13,
								name: 'COMPRAS',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 14,
								name: 'GESTIÓN DE RECEPCIÓN',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 6,
						name: 'GESTIÓN DE VENTAS',
						path: null,
						icon: 'mdiViewModule',
						groups: [],
						programs: [
							{
								id: 15,
								name: 'VENTAS',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 16,
								name: 'AUTORIZACIONES',
								path: null,
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
					{
						id: 4,
						name: 'MANTENIMIENTOS',
						path: null,
						icon: 'mdiViewModule',
						groups: [
							{
								id: 2,
								name: 'GESTIÓN DE ENTIDADES PERSONALES',
								path: null,
								icon: 'mdiAccount',
								programs: [
									{
										id: 17,
										name: 'CLIENTES',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 18,
										name: 'TRANSPORTISTAS',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 19,
										name: 'COLABORADORES',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
									{
										id: 23,
										name: 'PROVEEDORES',
										path: null,
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
						],
						programs: [],
					},
				],
			},
		],
	},
];

export const AGENCIES_DATA_TOMAS: IAgency[] = [
	{
		id: 4,
		name: 'CUENCA',
		modules: [
			{
				id: 1,
				name: 'VEHÍCULOS',
				path: null,
				icon: 'mdiSquareRoundedOutline',
				entorno: 'FRONT',
				submodules: [
					{
						id: 1,
						name: 'MANTENIMIENTOS',
						path: null,
						icon: 'mdiViewModule',
						groups: [
							{
								id: 1,
								name: 'GESTIÓN DE ENTIDADES PERSONALES',
								path: null,
								icon: 'mdiAccount',
								programs: [
									{
										id: 5,
										name: 'CLIENTES',
										path: '/nucleo/gestion-clientes',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
						],
						programs: [],
					},
				],
			},
			{
				id: 26,
				name: 'REPUESTOS',
				path: null,
				icon: 'mdiCarSpeedLimiter',
				entorno: 'BACKOFFICE',
				submodules: [
					{
						id: 11,
						name: 'MANTENIMIENTOS',
						path: '',
						icon: 'mdiFolder',
						groups: [],
						programs: [
							{
								id: 43,
								name: 'ORIGEN DE REPUESTOS',
								path: '/itsa/spare/origin',
								url: '/itsa/spare/origin',
								icon: 'mdiArchiveArrowDownOutline',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 44,
								name: 'MANT. REPUESTOS',
								path: '/itsa/spares',
								url: '/itsa/spares',
								icon: 'mdiCarWrench',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 45,
								name: 'MANT. R. EQUIVALENTES',
								path: '/itsa/spares-equivalents',
								icon: 'mdiSpaceStation',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 46,
								name: 'MANT. R. REEMPLAZO',
								path: '/itsa/spares-replacements',
								icon: 'mdiSpaceStation',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
				],
			},
			{
				id: 10,
				name: 'SEGURIDAD',
				path: 'seguridad',
				icon: 'mdiSecurity',
				entorno: 'BACKOFFICE',
				submodules: [
					{
						id: 8,
						name: 'MANTENIMIENTOS',
						path: '',
						icon: 'mdiFolder',
						groups: [
							{
								id: 3,
								name: 'GRUPO DE PRUEBA 1',
								path: '',
								icon: null,
								programs: [
									{
										id: 27,
										name: 'MODULOS GRUPO PRUEBA',
										path: '/itsa/security/maintenance/modules',
										icon: 'mdiLaptop',
										actions: {
											allActions: 1,
											read: 0,
											create: 0,
											update: 0,
											delete: 0,
										},
									},
								],
							},
						],
						programs: [
							{
								id: 26,
								name: 'PROGRAMAS',
								path: '/itsa/security/maintenance/programs',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
							{
								id: 25,
								name: 'MODULOS',
								path: '/itsa/security/maintenance/modules',
								icon: 'mdiLaptop',
								actions: {
									allActions: 1,
									read: 0,
									create: 0,
									update: 0,
									delete: 0,
								},
							},
						],
					},
				],
			},
		],
	},
];
