import {
	isArray,
	isEmpty,
	isNumber,
	isObject,
	isString,
	isUndefined,
	isValidEmailFormat,
	isValidMaskFormat,
} from './booleansChecks';
import { getInstance, securityApi } from './configAxios';
import { getFormatCurrency } from './currencies';
import { getCurrentDate } from './dates';
import {
	getDropdownFormattedOptions,
	getFormattedAddress,
	getFormattedFieldValue,
	getFormattedSchemaValues,
	getLabelFromValue,
	getSchemaColumns,
	getSchemaFields,
	getNumberFromStorage,
	getStringFromStorage,
} from './formats';
import {
	cleanObject,
	createValueLabelMap,
	filterMenuSidebar,
	filterMenuTree,
	findLastChild,
	generateFilteredMenu,
	getAllMenuKeys,
	getMappedOptionFromAPI,
	getMappedOptionFromLocal,
	getNestedValue,
	hasAllRequiredFields,
	mapPermissionsToMenuFormat,
} from './objects';
import { transformModuleToMenuData } from './menu/menuDataTransformer';
import { clearLocalStorage } from './session';
import { capitalize, isRouteActive, toTitleCase, getMicroFrontendByPath, joinUrl, isNumericOnly, filterNumericOnly, filterPositiveNumbersOnly } from './strings';
import {
	addOrderParamIfMissing,
	buildQueryParams,
	cleanPath,
	clearURLParams,
	fillRoute,
	getParamsFromURL,
	getQueryParam,
	updateURLParams,
} from './urls';

export {
	addOrderParamIfMissing,
	buildQueryParams,
	capitalize,
	cleanObject,
	cleanPath,
	clearLocalStorage,
	clearURLParams,
	createValueLabelMap,
	fillRoute,
	filterMenuSidebar,
	filterMenuTree,
	filterNumericOnly,
	filterPositiveNumbersOnly,
	findLastChild,
	getNumberFromStorage,
	getStringFromStorage,
	getInstance,
	generateFilteredMenu,
	getAllMenuKeys,
	getCurrentDate,
	getDropdownFormattedOptions,
	getFormatCurrency,
	getFormattedAddress,
	getFormattedFieldValue,
	getFormattedSchemaValues,
	getLabelFromValue,
	getMappedOptionFromAPI,
	getMappedOptionFromLocal,
	getNestedValue,
	getParamsFromURL,
	getQueryParam,
	getSchemaColumns,
	getSchemaFields,
	getMicroFrontendByPath,
	hasAllRequiredFields,
	isArray,
	isEmpty,
	isNumber,
	isNumericOnly,
	isObject,
	isRouteActive,
	isString,
	isUndefined,
	isValidEmailFormat,
	isValidMaskFormat,
	joinUrl,
	mapPermissionsToMenuFormat,
	securityApi,
	toTitleCase,
	transformModuleToMenuData,
	updateURLParams,
};
